version: '3'
services:
  postgres: 
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gingo
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "patrike@alura.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

# para descobrir o ip digite "hostname -i" dentro da imagem do postgres